
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('genre').del()
    .then(function () {
      // Inserts seed entries
      return knex('genre').insert([
        {id: 1, name: 'action'},
        {id: 2, name: 'adventure'},
        {id: 3, name: 'comedy'},
        {id: 4, name: 'crime'},
        {id: 5, name: 'mystery'},
        {id: 6, name: 'fantasy'},
        {id: 7, name: 'historical'},
        {id: 8, name: 'horror'},
        {id: 9, name: 'romance'},
        {id: 10, name: 'satire'},
        {id: 11, name: 'science fiction'},
        {id: 12, name: 'thriller'},
        {id: 13, name: 'western'},
        {id: 14, name: 'animation'},
        {id: 15, name: 'drama'},
        {id: 16, name: 'war'},
        {id: 17, name: 'sports'},
        {id: 18, name: 'slasher'},
        {id: 19, name: `children's film`},
        {id: 20, name: 'superhero'},
        {id: 21, name: 'indie film'},
        {id: 22, name: 'shooter'},
        {id: 23, name: 'puzzle'},
        {id: 24, name: 'fighting'},
        {id: 25, name: 'racing'},
        {id: 26, name: 'role-playing'},
        {id: 27, name: 'simulation'},
        {id: 28, name: 'strategy'},
        {id: 29, name: 'historical fiction'},
        {id: 30, name: 'biography'},
        {id: 31, name: 'autobiography'},
        {id: 32, name: 'cookbook'},
        {id: 33, name: 'essay'},
        {id: 34, name: 'memoir'},
        {id: 35, name: 'poetry'},
        {id: 36, name: 'self-help'},
        {id: 37, name: 'true crime'},
        {id: 38, name: 'crafts/hobbies'},
        {id: 39, name: 'business'},
        {id: 40, name: 'art'},
        {id: 41, name: `children's`},
        {id: 42, name: 'humanities'},
        {id: 43, name: 'technology'},
        {id: 44, name: 'science'},
        {id: 45, name: 'computer science'},
        {id: 46, name: 'fiction'},
      ]);
    });
};
